// Palette
export const C = {
  indigo:         '#2f3e6b',
  indigoDark:     '#212c4d',
  indigoLight:    '#e8ecf7',
  terracotta:     '#b3502a',
  terracottaDark: '#8c3c1d',
  terracottaLight:'#f9ece6',
  gold:           '#c79a3f',
  goldLight:      '#fdf4e1',
  green:          '#3e6e4a',
  greenLight:     '#ebf5ee',
  red:            '#a8392f',
  redLight:       '#fdf0ee',
  paper:          '#f7f1e6',
  paperDim:       '#efe6d4',
  ink:            '#1c1410',
  inkMuted:       '#766a5c',
  line:           'rgba(28,20,16,0.12)',
  white:          '#ffffff',
}

// Shared style objects
export const S = {
  card: {
    background: C.white,
    border: `1px solid ${C.line}`,
    borderRadius: 10,
    padding: 22,
    boxShadow: '0 4px 16px rgba(28,20,16,0.08)',
    marginBottom: 20,
  },
  label: {
    display: 'block',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: C.inkMuted,
    marginBottom: 5,
    marginTop: 14,
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${C.line}`,
    borderRadius: 7,
    fontSize: 14,
    background: C.paperDim,
    color: C.ink,
    boxSizing: 'border-box',
  },
  select: {
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${C.line}`,
    borderRadius: 7,
    fontSize: 14,
    background: C.paperDim,
    color: C.ink,
    boxSizing: 'border-box',
  },
  btnPrimary: {
    background: C.terracotta,
    color: '#fff',
    border: 'none',
    padding: '11px 22px',
    borderRadius: 7,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    width: '100%',
    marginTop: 18,
  },
  btnAdd: {
    background: C.indigo,
    color: '#fff',
    border: 'none',
    padding: '10px 28px',
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: 14,
  },
  btnDanger: {
    background: 'transparent',
    color: C.red,
    border: `1px solid ${C.red}`,
    padding: '4px 10px',
    borderRadius: 6,
    fontSize: 12,
    cursor: 'pointer',
  },
  btnNav: (active) => ({
    background: active ? 'rgba(255,255,255,0.18)' : 'transparent',
    color: '#fff',
    border: '1px solid rgba(255,255,255,0.3)',
    padding: '6px 14px',
    borderRadius: 6,
    fontSize: 13,
    cursor: 'pointer',
  }),
  sectionTitle: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 2,
    color: C.terracotta,
    fontWeight: 700,
    marginBottom: 14,
  },
  th: {
    textAlign: 'left',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: C.inkMuted,
    padding: '8px 10px',
    borderBottom: `2px solid ${C.line}`,
  },
  td: {
    padding: '10px',
    borderBottom: `1px solid ${C.line}`,
    verticalAlign: 'middle',
    fontSize: 14,
  },
  tagIn:  { display: 'inline-block', padding: '3px 9px', borderRadius: 999, fontSize: 11, fontWeight: 600, background: 'rgba(62,110,74,0.12)',  color: '#3e6e4a' },
  tagOut: { display: 'inline-block', padding: '3px 9px', borderRadius: 999, fontSize: 11, fontWeight: 600, background: 'rgba(168,57,47,0.12)', color: '#a8392f' },
  tagRole: (role) => ({
    display: 'inline-block', padding: '3px 10px', borderRadius: 999, fontSize: 11, fontWeight: 700, letterSpacing: 0.5,
    background: role === 'boss' ? C.goldLight : role === 'admin' ? C.indigoLight : C.paperDim,
    color:      role === 'boss' ? C.gold      : role === 'admin' ? C.indigo      : C.inkMuted,
    border: `1px solid ${role === 'boss' ? C.gold : role === 'admin' ? C.indigo : C.line}`,
    marginLeft: 8,
  }),
  totalBoxIn:  { flex: 1, minWidth: 150, background: '#ebf5ee', border: '1px solid rgba(62,110,74,0.2)',  borderRadius: 10, padding: 18 },
  totalBoxOut: { flex: 1, minWidth: 150, background: '#fdf0ee', border: '1px solid rgba(168,57,47,0.2)', borderRadius: 10, padding: 18 },
  totalBoxNet: { flex: 1, minWidth: 150, background: '#e8ecf7', border: '1px solid rgba(47,62,107,0.2)',  borderRadius: 10, padding: 18 },
}
